//! Publish generated summaries to a git repository.
//!
//! Handles cloning (if needed), copying output, committing, and pushing.

use anyhow::{Context, Result};
use chrono::NaiveDate;
use std::path::{Path, PathBuf};
use std::process::Command;
use tracing::{debug, info};

const DEFAULT_REMOTE: &str = "https://github.com/eserilev/eth-r-d-ai-summary.git";
const DEFAULT_BRANCH: &str = "main";

/// Configuration for publishing summaries.
#[derive(Debug, Clone)]
pub struct PublishConfig {
    /// Git remote URL
    pub remote: String,
    /// Branch to push to
    pub branch: String,
    /// Local path for the publish repo clone
    pub repo_path: PathBuf,
}

impl Default for PublishConfig {
    fn default() -> Self {
        Self {
            remote: DEFAULT_REMOTE.to_string(),
            branch: DEFAULT_BRANCH.to_string(),
            repo_path: PathBuf::from("/tmp/eth-r-d-ai-summary"),
        }
    }
}

/// Check which dates have already been published for a given channel.
///
/// Looks at the directory structure: `{channel}/{YYYY}/{MM}/{DD}/_index.md`
/// Returns a set of dates that already have summaries.
pub fn published_dates(
    config: &PublishConfig,
    channel_name: &str,
) -> Result<std::collections::HashSet<chrono::NaiveDate>> {
    use std::collections::HashSet;

    let mut dates = HashSet::new();

    // Ensure repo is available
    if !config.repo_path.join(".git").exists() {
        // Try to clone, but don't fail if we can't — just return empty
        if ensure_repo(config).is_err() {
            debug!("Could not access publish repo for date check, assuming nothing published");
            return Ok(dates);
        }
    }

    let channel_dir = config.repo_path.join(channel_name);
    if !channel_dir.exists() {
        return Ok(dates);
    }

    // Walk {YYYY}/{MM}/{DD}/_index.md
    for year_entry in std::fs::read_dir(&channel_dir)? {
        let year_entry = year_entry?;
        if !year_entry.file_type()?.is_dir() {
            continue;
        }
        let year_name = year_entry.file_name().to_string_lossy().to_string();

        for month_entry in std::fs::read_dir(year_entry.path())? {
            let month_entry = month_entry?;
            if !month_entry.file_type()?.is_dir() {
                continue;
            }
            let month_name = month_entry.file_name().to_string_lossy().to_string();

            for day_entry in std::fs::read_dir(month_entry.path())? {
                let day_entry = day_entry?;
                if !day_entry.file_type()?.is_dir() {
                    continue;
                }
                let day_name = day_entry.file_name().to_string_lossy().to_string();

                // Verify _index.md exists (it's a real summary, not just a directory)
                if day_entry.path().join("_index.md").exists() {
                    let date_str = format!("{}-{}-{}", year_name, month_name, day_name);
                    if let Ok(date) = chrono::NaiveDate::parse_from_str(&date_str, "%Y-%m-%d") {
                        dates.insert(date);
                    }
                }
            }
        }
    }

    debug!(
        channel = channel_name,
        count = dates.len(),
        "Found already-published dates"
    );
    Ok(dates)
}

/// Publish the output directory contents to the configured git repo.
///
/// Steps:
/// 1. Clone or pull the repo
/// 2. Copy output files into the repo
/// 3. Commit with a descriptive message
/// 4. Push to remote
pub fn publish(
    output_dir: &Path,
    channels: &[String],
    from: NaiveDate,
    to: NaiveDate,
    config: &PublishConfig,
) -> Result<()> {
    info!("Publishing summaries to {}", config.remote);

    // Step 1: Ensure repo is cloned and up to date
    ensure_repo(config)?;

    // Step 2: Copy output files into the repo
    copy_output(output_dir, &config.repo_path)?;

    // Step 3: Stage all changes
    git_cmd(&config.repo_path, &["add", "-A"])?;

    // Check if there's anything to commit
    let status = git_cmd_output(&config.repo_path, &["status", "--porcelain"])?;
    if status.trim().is_empty() {
        info!("No changes to publish");
        return Ok(());
    }

    // Step 4: Commit
    let date_range = if from == to {
        from.to_string()
    } else {
        format!("{} to {}", from, to)
    };
    let channels_str = channels.join(", ");
    let commit_msg = format!(
        "Add summaries: {} ({})\n\nChannels: {}\nGenerated by eth-discord-summarizer",
        channels_str, date_range, channels_str
    );

    git_cmd(&config.repo_path, &["commit", "-m", &commit_msg])?;

    // Step 5: Push
    git_cmd(&config.repo_path, &["push", "origin", &config.branch])?;

    info!("Successfully published to {}", config.remote);
    Ok(())
}

/// Ensure the publish repo is cloned and on the correct branch.
fn ensure_repo(config: &PublishConfig) -> Result<()> {
    if config.repo_path.join(".git").exists() {
        // Repo exists — pull latest
        debug!("Pulling latest from {}", config.remote);
        git_cmd(&config.repo_path, &["fetch", "origin"])?;
        git_cmd(
            &config.repo_path,
            &["reset", "--hard", &format!("origin/{}", config.branch)],
        )?;
    } else {
        // Clone fresh
        info!("Cloning {} to {}", config.remote, config.repo_path.display());
        std::fs::create_dir_all(config.repo_path.parent().unwrap_or(Path::new("/tmp")))?;

        let output = Command::new("git")
            .args([
                "clone",
                "--branch",
                &config.branch,
                &config.remote,
                config.repo_path.to_str().unwrap_or(""),
            ])
            .output()
            .context("Failed to run git clone")?;

        if !output.status.success() {
            // Maybe the branch doesn't exist yet — clone default and create it
            let output2 = Command::new("git")
                .args([
                    "clone",
                    &config.remote,
                    config.repo_path.to_str().unwrap_or(""),
                ])
                .output()
                .context("Failed to run git clone (no branch)")?;

            if !output2.status.success() {
                let stderr = String::from_utf8_lossy(&output2.stderr);
                anyhow::bail!("git clone failed: {}", stderr);
            }

            // Create and switch to the target branch
            git_cmd(
                &config.repo_path,
                &["checkout", "-b", &config.branch],
            )
            .ok(); // might already be on it
        }
    }

    Ok(())
}

/// Copy output directory contents into the repo, preserving structure.
fn copy_output(output_dir: &Path, repo_path: &Path) -> Result<()> {
    if !output_dir.exists() {
        anyhow::bail!("Output directory does not exist: {}", output_dir.display());
    }

    // Use cp -r to copy while preserving directory structure
    let output = Command::new("cp")
        .args(["-r", "--no-preserve=ownership"])
        .arg(format!("{}/.", output_dir.display()))
        .arg(repo_path.to_str().unwrap_or(""))
        .output()
        .context("Failed to copy output to publish repo")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("cp failed: {}", stderr);
    }

    debug!(
        "Copied output from {} to {}",
        output_dir.display(),
        repo_path.display()
    );
    Ok(())
}

/// Run a git command in the given directory.
fn git_cmd(repo: &Path, args: &[&str]) -> Result<()> {
    let output = Command::new("git")
        .current_dir(repo)
        .args(args)
        .output()
        .with_context(|| format!("Failed to run git {}", args.join(" ")))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("git {} failed: {}", args.join(" "), stderr);
    }

    Ok(())
}

/// Run a git command and return stdout.
fn git_cmd_output(repo: &Path, args: &[&str]) -> Result<String> {
    let output = Command::new("git")
        .current_dir(repo)
        .args(args)
        .output()
        .with_context(|| format!("Failed to run git {}", args.join(" ")))?;

    Ok(String::from_utf8_lossy(&output.stdout).to_string())
}
